apiVersion: apps/v1
kind: Deployment
metadata:
  name: geolocalizacion-deployment
  labels:
    app: ms-geolocalizacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-geolocalizacion
  template:
    metadata:
      labels:
        app: ms-geolocalizacion
    spec:
      containers:
      - name: ms-geolocalizacion
        image: 782424855823.dkr.ecr.us-east-1.amazonaws.com/ms-geolocalizacion:${IMAGE_TAG}
        ports:
        - containerPort: 8083
        env:
        - name: DB_URL
          value: "jdbc:postgresql://sanosdb-service:5432/db_geolocalizacion"
        - name: DB_USERNAME
          value: "admin"
        - name: DB_PASSWORD
          value: "admin"
        - name: EUREKA_URL
          value: "http://eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: geolocalizacion-service
spec:
  type: ClusterIP
  selector:
    app: ms-geolocalizacion
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083